### ISSUE TITLE
Allow drivers to propose a different rate for a ride request

### ISSUE THREAD

**Issue by p2prider** [p2prider/p2prider#4]
Based on question from https://np.reddit.com/r/bangalore/comments/thvlcv/a_nonprofit_project_to_fix_the_state_of/i1a91mk/

> [enthuvadey](https://reddit.com/user/enthuvadey) 1 point 8 minutes ago 
> Let's say, a new driver joins the service, who is from a poorer financial background. So he is willing to take a ride for cheaper rate. How will the app handle this situation?

**Comment by ashwingattani** [comment]
[As mentioned here](https://github.com/p2prider/p2prider/issues/12#issuecomment-1073172049), we can ask drivers to set a base fare, drivers can select the base fare from a range given in the application. and total fare calculation can be based upon this rate.

**Comment by p2prider** [comment]
Sure, let's follow up the discussion over there.
